from typing import Mapping, Any, Iterable, Optional

from hdm.types.mappings import ResultMapping


class Storage:
    def add_table(self, tablename: str, primary_key: Iterable[str], fields: Iterable[str]): ...
    def setup(self): ...

    def find_one(self, tablename: str, criteria: dict) -> Optional[ResultMapping]: ...
    def find_many(self, tablename: str, criteria: dict, *, limit=None, offset=None) -> Iterable[ResultMapping]: ...
    def insert(self, tablename: str, values: dict) -> ResultMapping: ...
    def update(self, tablename: str, identity: Mapping[str, Any], values: dict) -> None: ...
    def delete(self, tablename, identity: dict): ...
